/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package dankery;

public class App {

    public static void main(String[] args) {
        String bakeryName = "cool baked things";
//        firstDemo();
//        Goal: take in information from outside the app and use it to run the app
//        System.out.println(args[0] + args[1] + args[2] + args[3]);
        Bakery bakeryFromCommandLine = new Bakery(args[0]);
        System.out.println(bakeryFromCommandLine);
        if(args[0].equals("dumb")){
            System.out.println("why you gotta be like that");
        }
    }

    public static void firstDemo(){
        Pastry bearclaw = new Pastry();
        bearclaw.shape = "oval-rectangle";
        System.out.println(bearclaw.taste + " " + bearclaw.shape);
        Pastry sconey = new Pastry("triangle", "strawberries", 9, false);
        System.out.println(sconey.taste + " " + sconey.shape);
        System.out.println(sconey);
        System.out.println(
                "all pastries are " +
                        Pastry.taste +
                        " because taste is statically true for all Pastries");
        System.out.println(bearclaw.taste);
        System.out.println(bearclaw);
        bearclaw.eat();
        sconey.eat();

        Pastry.taste = "definitely not yummy ;)";
        System.out.println(bearclaw);
        sconey.taste = "awesome";
        System.out.println(bearclaw);

        Bakery beesTreats = new Bakery("Bee's Sweet Treats");
        System.out.println(beesTreats);
        beesTreats.pastries.add(bearclaw);
        beesTreats.pastries.add(sconey);
        System.out.println(beesTreats);
    }
}
