/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package videoGame;

import org.junit.Test;

import java.util.List;

import static org.junit.Assert.*;

public class LibraryTest {
    @Test public void testEverything(){
        LumberJack lumberJackie = new LumberJack();
        LumberJack lumberJill = new LumberJack();
        System.out.println(lumberJackie.fight(lumberJill));

        Tree tree = new Tree("whispering willowy");
//        System.out.println(tree.fight(lumberJackie));
//        System.out.println(lumberJill.fight(tree));
//
//        EngageAble[] fighters = {lumberJackie, lumberJill, tree};
//        for(EngageAble fighter : fighters){
//            for(EngageAble opponent : fighters){
//                System.out.println(fighter.fight(opponent));
//            }
//        }

        Wookie chewy = new Wookie();
        Wookie chewy2 = new Wookie();
        Wookie chewy3 = new Wookie();

        FlowerMonster flowerMonster1 = new FlowerMonster();
        new FlowerMonster();
        new FlowerMonster();
        lumberJackie.crawl();
        lumberJackie.crawl();
        lumberJackie.crawl();
        lumberJill.walk();
        lumberJill.walk();
        lumberJill.walk();
    }

    @Test public void testDynamicTypes(){
        Quest<Tree, String, Integer, List, int[]> questy = new Quest();
//        questy.monsters.add(new LumberJack());

        Quest<Wookie, String, Integer, List, int[]> wookieQuest = new Quest<>();
        wookieQuest.monsters.add(new Wookie());
//        wookieQuest.monsters.add(new LumberJack());

        Quest<EngageAble, String, String, String, String> multipleMonsterQuest = new Quest();
        multipleMonsterQuest.monsters.add(new LumberJack());
        multipleMonsterQuest.monsters.add(new Wookie());
        multipleMonsterQuest.monsters.add(new Tree("herald"));
        multipleMonsterQuest.monsters.add(new FlowerMonster());
    }
}
